[package]
name = "ayaka-bindings-types"
version = "0.1.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2021"

[dependencies]
ayaka-script = { path = "../ayaka-script" }
anyhow = "1.0"
fallback = "0.1"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
log = { version = "0.4", features = ["serde"] }
bitflags = "1.3"
trylog = "0.2"
