[package]
name = "native"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ayaka-model = { path = "../../utils/ayaka-model" }
flutter_rust_bridge = "1"

[build-dependencies]
flutter_rust_bridge_codegen = "1"
