[package]
name = "ayaka-gui"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.0", features = [] }

[dependencies]
ayaka-runtime = { path = "../../../utils/ayaka-runtime" }
flexi_logger = { version = "0.23", default-features = false, features = ["colors"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0", features = ["cli", "protocol-all", "window-all"] }
tauri-plugin-localhost = "0.1"
portpicker = "0.1"
trylog = "0.2"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
