[package]
name = "ayaka-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
ayaka-bindings-types = { path = "../ayaka-bindings-types" }
ayaka-script-types = { path = "../ayaka-script-types", features = ["rt-format"] }
ayaka-script = { path = "../ayaka-script" }
fallback = "0.1"
language-matcher = "0.1"
icu_locid = { version = "1.0.0-beta1", features = ["std"] }
sys-locale = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
rmp-serde = "1.1"
anyhow = "1.0"
wasmer = "3.0"
wasmer-wasi = "2.3"
unicode-width = "0.1"
rt-format = "0.3"
tokio = { version = "1", features = ["fs", "macros"] }
tokio-stream = { version = "0.1", features = ["fs"] }
stream-future = "0.3"
futures-util = "0.3"
dirs = "4.0"
scopeguard = "1.1"

[dev-dependencies]
tokio = { version = "1", features = ["parking_lot", "rt"] }
