[package]
name = "ayaka-model"
description = "Ayaka high-level runtime."
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ayaka-plugin = { workspace = true }
ayaka-runtime = { workspace = true }
serde = { workspace = true, features = ["derive"] }
stream-future = { workspace = true }
trylog = { workspace = true }

[dev-dependencies]
ayaka-plugin-wasmi = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tempfile = "3"
serde_json = "1"
